const SUPABASE_URL='https://glttqzvewnchpddtkfde.supabase.co';
const SUPABASE_KEY='sb_publishable_lazb-Ub8XQE83jSMHOj7LQ_PdugUzSr';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);let me=null,campaign=null,cities=[],sectors=[],streets=[],households=[],visits=[],teams=[],members=[],teamStreets=[],presence=[],map=null,markers=[],helpTeam=null,lastAction=null,imported=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(s,undo=false){$('toast').innerHTML=esc(s)+(undo?' <button onclick="undoLast()">Annuler</button>':'');$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',undo?5000:2500)}
function setSync(s,w=false){$('syncState').textContent=(w?'🟠 ':'🟢 ')+s;$('syncState').className='muted sync '+(w?'warn':'ok')}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session)await enter(session.user);else showAuth();sb.auth.onAuthStateChange(async(e,s)=>{if(e==='SIGNED_IN'&&s)await enter(s.user);if(e==='SIGNED_OUT')showAuth()});window.addEventListener('online',()=>{setSync('Connexion retrouvée');flushQueue()});window.addEventListener('offline',()=>setSync('Hors connexion',true))}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('tabs').classList.add('hidden')}
async function enter(user){const {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error)return $('authMsg').textContent='Compte créé. Vérifie ton e-mail puis reconnecte-toi.';me=p;if(!p.active){$('authMsg').textContent='Ton compte attend la validation de l’administrateur.';await sb.auth.signOut();return}$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('tabs').classList.remove('hidden');document.body.classList.toggle('isAdmin',p.role==='admin');$('who').textContent=`${p.full_name||p.email} · ${p.role}`;$('profileInfo').innerHTML=`<b>${esc(p.full_name||'')}</b><br>${esc(p.email||'')}<br><span class="pill">${esc(p.role)}</span>`;await loadAll();subscribe();page('home')}
async function loadAll(){setSync('Synchronisation…');const c=await sb.from('campaigns').select('*').eq('active',true).order('year',{ascending:false}).limit(1).maybeSingle();campaign=c.data;if(!campaign)return setSync('Aucune campagne active',true);$('campaignYear').textContent=campaign.year;
const [ci,se,st,h,v,t,tm,ts,pr]=await Promise.all([sb.from('cities').select('*').eq('active',true).order('name'),sb.from('sectors').select('*,cities(name,postal_code)').eq('active',true).order('name'),sb.from('streets').select('*').eq('active',true).order('name'),sb.from('households').select('*').eq('active',true).order('street').order('house_number'),sb.from('visits').select('*').eq('campaign_id',campaign.id),sb.from('teams').select('*').eq('campaign_id',campaign.id).eq('active',true),sb.from('team_members').select('*'),sb.from('team_streets').select('*'),sb.from('visit_presence').select('*')]);
cities=ci.data||[];sectors=se.data||[];streets=st.data||[];households=h.data||[];visits=v.data||[];teams=t.data||[];members=tm.data||[];teamStreets=ts.data||[];presence=pr.data||[];renderFilters();renderHouses();renderStats();renderMap();const mine=households.filter(h=>myTeamIds().includes(teamForHouse(h)));if(mine.length&&mine.every(h=>visitFor(h.id)?.status==='fait')){const needy=teams.map(t=>({t,n:households.filter(h=>teamForHouse(h)===t.id&&visitFor(h.id)?.status!=='fait').length})).filter(x=>x.n>0&&!myTeamIds().includes(x.t.id)).sort((a,b)=>b.n-a.n)[0];if(needy){$('helpMode').classList.remove('hidden');$('helpMode').innerHTML=`🎉 Votre secteur est terminé. <b>${needy.n} maison(s)</b> restent à ${esc(needy.t.name)}. Utilisez 🤝 Aider pour leur donner un coup de main.`}}if(me.role==='admin')await renderAdmin();setSync(navigator.onLine?'Synchronisé':'Hors connexion',!navigator.onLine)}
function myTeamIds(){return members.filter(x=>x.user_id===me.id).map(x=>x.team_id)}
function visitFor(id){return visits.find(v=>v.household_id===id)}
function teamForHouse(h){const x=teamStreets.find(ts=>ts.street_id===h.street_id);return x?.team_id||null}
function visibleHouses(){if(me.role==='admin'||me.role==='responsable')return households;const ids=myTeamIds();return households.filter(h=>ids.includes(teamForHouse(h))||(helpTeam&&teamForHouse(h)===helpTeam))}
function renderFilters(){const ids=myTeamIds();$('teamView').innerHTML='<option value="">Mon équipe / mes secteurs</option>'+teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('sectorSelect').innerHTML='<option value="">Tous les secteurs</option>'+sectors.map(s=>`<option value="${s.id}">${esc(s.cities?.name||'')} — ${esc(s.name)}</option>`).join('');$('assignTeam').innerHTML=teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('importCity').innerHTML=cities.map(c=>`<option value="${c.id}">${esc(c.name)} ${esc(c.postal_code||'')}</option>`).join('')}
function renderStats(){const list=visibleHouses(),vv=visits.filter(v=>list.some(h=>h.id===v.household_id));let done=0,redo=0,cal=0,amt=0,pay={};vv.forEach(v=>{if(v.status==='fait')done++;if(['absent','a_repasser'].includes(v.status))redo++;cal+=+v.calendars_count||0;amt+=+v.amount||0;if(v.payment_method)pay[v.payment_method]=(pay[v.payment_method]||0)+(+v.amount||0)});$('sTotal').textContent=list.length;$('sDone').textContent=done;$('sRedo').textContent=redo;$('sRemain').textContent=Math.max(0,list.length-done);$('sCalendars').textContent=cal;$('sAmount').textContent=amt.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});$('paymentStats').textContent=Object.entries(pay).map(([k,v])=>`${k}: ${v.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}`).join(' · ')||'Aucun encaissement';
$('teamProgress').innerHTML=teams.map(t=>{const hs=households.filter(h=>teamForHouse(h)===t.id),d=hs.filter(h=>visitFor(h.id)?.status==='fait').length,p=hs.length?Math.round(d/hs.length*100):0;return `<div class="street"><b>${esc(t.name)}</b> — ${d}/${hs.length} (${p} %)<div class="progress"><span style="width:${p}%"></span></div></div>`}).join('')||'<span class="muted">Crée les équipes pour afficher leur progression.</span>'}
function renderHouses(){if(!$('houses'))return;const sid=$('sectorSelect').value,tid=$('teamView').value,fs=$('filterStatus').value,q=$('searchHouse').value.toLowerCase();let list=visibleHouses().filter(h=>(!sid||h.sector_id===sid)&&(!tid||teamForHouse(h)===tid));list=list.filter(h=>{const v=visitFor(h.id),st=v?.status||'a_faire';return(!fs||st===fs)&&(`${h.house_number||''} ${h.street||''} ${h.locality||''} ${h.permanent_note||''}`.toLowerCase().includes(q))});$('houses').innerHTML=list.map(h=>houseHTML(h)).join('')||'<div class="card muted">Aucun foyer correspondant.</div>'}
function houseHTML(h){const v=visitFor(h.id)||{},st=v.status||'a_faire',busy=presence.find(p=>p.household_id===h.id&&new Date(p.expires_at)>new Date()&&p.user_id!==me.id),cl=st==='fait'?'done':st==='refus'?'refus':(['absent','a_repasser'].includes(st)?'redo':'');return `<div class="house ${cl}" id="h-${h.id}"><div class="address">${esc(h.house_number||'')} ${esc(h.street||'')}</div>${busy?`<div class="pill">⚠️ Un autre membre consulte cette maison</div>`:""}<div class="muted">${esc(h.locality||'')} ${esc(h.city_name||'')}</div>${h.note_category?`<span class="pill">${esc(h.note_category)}</span>`:''}${h.preferred_time?`<span class="pill">🕒 ${esc(h.preferred_time)}</span>`:''}${h.permanent_note?`<div>📝 ${esc(h.permanent_note)}</div>`:''}<div class="status"><button class="green" onclick="openDone('${h.id}')">✅ FAIT</button><button class="orange" onclick="quickStatus('${h.id}','absent')">🚪 ABSENT</button><button class="orange" onclick="quickStatus('${h.id}','a_repasser')">🔄 À REPASSER</button><button class="gray" onclick="quickStatus('${h.id}','refus')">⛔ REFUS</button></div><div id="done-${h.id}" class="${st==='fait'?'':'hidden'}"><br><div class="grid g2"><input id="cal-${h.id}" type="number" min="0" placeholder="Calendriers" value="${v.calendars_count??1}"><input id="amt-${h.id}" type="number" min="0" step=".01" placeholder="Don €" value="${v.amount??''}"><select id="pay-${h.id}"><option value="">Paiement</option>${['especes','carte','cheque','autre'].map(x=>`<option value="${x}" ${v.payment_method===x?'selected':''}>${x}</option>`).join('')}</select><input id="com-${h.id}" placeholder="Commentaire visite" value="${esc(v.visit_comment||'')}"></div><br><div class="row"><button class="btn" onclick="saveVisit('${h.id}','fait')">Valider</button><button class="btn alt" onclick="editNote('${h.id}')">📝 Infos maison</button><button class="btn alt" onclick="navigateTo('${h.id}')">🧭 M'y rendre</button><button class="btn alt" onclick="receiptFor('${h.id}')">🧾 Reçu</button></div></div></div>`}
window.openDone=async id=>{const now=new Date(),exp=new Date(Date.now()+5*60*1000);const other=presence.find(p=>p.household_id===id&&new Date(p.expires_at)>now&&p.user_id!==me.id);if(other&&!confirm("Cette maison est déjà ouverte par un autre membre. Continuer quand même ?"))return;await sb.from('visit_presence').upsert({household_id:id,user_id:me.id,started_at:now.toISOString(),expires_at:exp.toISOString()});$('done-'+id).classList.remove('hidden')};window.quickStatus=(id,s)=>saveVisit(id,s);
async function saveVisit(id,status){const old=visitFor(id)||{},owner=teamForHouse(households.find(h=>h.id===id)),payload={campaign_id:campaign.id,household_id:id,team_id:helpTeam||owner||old.team_id||null,original_team_id:owner||null,helper_mode:!!helpTeam,status,calendars_count:+($('cal-'+id)?.value||0),amount:+($('amt-'+id)?.value||0),payment_method:$('pay-'+id)?.value||null,visit_comment:$('com-'+id)?.value||null,visited_by:me.id,visited_at:new Date().toISOString(),updated_at:new Date().toISOString(),client_updated_at:new Date().toISOString()};lastAction={id,old:{...old}};if(!navigator.onLine){queue(payload);applyLocal(payload);return toast('Enregistré hors connexion',true)}const {data,error}=await sb.from('visits').upsert(payload,{onConflict:'campaign_id,household_id'}).select().single();if(error){queue(payload);applyLocal(payload);setSync('Saisie en attente',true);return toast('Réseau faible : saisie conservée',true)}applyLocal(data);await sb.from('visit_presence').delete().eq('household_id',id).eq('user_id',me.id);toast('Maison enregistrée',true)}
function applyLocal(v){const i=visits.findIndex(x=>x.household_id===v.household_id);if(i>=0)visits[i]={...visits[i],...v};else visits.push(v);renderHouses();renderStats()}
function queue(p){const q=JSON.parse(localStorage.getItem('visitQueue')||'[]');q.push(p);localStorage.setItem('visitQueue',JSON.stringify(q));setSync(`${q.length} saisie(s) à synchroniser`,true)}
async function flushQueue(){let q=JSON.parse(localStorage.getItem('visitQueue')||'[]');if(!q.length)return;const left=[];for(const p of q){const {error}=await sb.from('visits').upsert(p,{onConflict:'campaign_id,household_id'});if(error)left.push(p)}localStorage.setItem('visitQueue',JSON.stringify(left));if(!left.length){toast('Saisies synchronisées');loadAll()}else setSync(`${left.length} saisie(s) en attente`,true)}
window.undoLast=async()=>{if(!lastAction)return;const {id,old}=lastAction;if(old.id){await sb.from('visits').update({status:old.status,calendars_count:old.calendars_count,amount:old.amount,payment_method:old.payment_method,visit_comment:old.visit_comment,updated_at:new Date().toISOString()}).eq('id',old.id)}else await sb.from('visits').delete().eq('campaign_id',campaign.id).eq('household_id',id);lastAction=null;await loadAll();toast('Dernière action annulée')}
window.editNote=async id=>{const h=households.find(x=>x.id===id),choices='🐕 Chien / 🚪 Portail / 👴 Personne âgée / 🌙 Passer le soir / ⚠️ Accès difficile / Autre';const cat=prompt('Information rapide : '+choices,h.note_category||'');if(cat===null)return;const note=prompt('Précision éventuelle',h.permanent_note||'');if(note===null)return;const time=prompt('Horaire conseillé : matin / midi / après-midi / avant 18 h / soir',h.preferred_time||'');if(time===null)return;const {data,error}=await sb.rpc('update_household_note',{p_household_id:id,p_permanent_note:note,p_note_category:cat,p_preferred_time:time});if(error)return toast(error.message);Object.assign(h,data);renderHouses();toast('Information conservée pour les prochaines années')}
window.receiptFor=async id=>{const v=visitFor(id),h=households.find(x=>x.id===id);if(!v?.id)return toast("Valide d'abord le passage");const name=prompt("Nom et prénom de la personne pour le reçu",'');if(name===null)return;const addr=prompt("Adresse du reçu",`${h.house_number||''} ${h.street||''}`.trim());if(addr===null)return;const pc=prompt("Code postal",h.postal_code||'');if(pc===null)return;const city=prompt("Commune",h.city_name||h.locality||'');if(city===null)return;const email=prompt("E-mail du destinataire (facultatif pour générer seulement)",'');if(email===null)return;const {data,error}=await sb.rpc('create_receipt_for_visit',{p_visit_id:v.id,p_recipient_email:email||null,p_recipient_name:name||null,p_recipient_address:addr||null,p_recipient_postal_code:pc||null,p_recipient_city:city||null});if(error)return toast(error.message);toast(email?`Reçu ${data.receipt_number} préparé pour envoi`:`Reçu ${data.receipt_number} créé`)};
window.navigateTo=id=>{const h=households.find(x=>x.id===id);if(h?.latitude&&h?.longitude)location.href=`https://maps.apple.com/?daddr=${h.latitude},${h.longitude}`;else location.href=`https://maps.apple.com/?daddr=${encodeURIComponent((h.house_number||'')+' '+(h.street||'')+' '+(h.city_name||''))}`}
$('helpBtn').onclick=()=>{const choices=teams.filter(t=>!myTeamIds().includes(t.id));if(!choices.length)return toast('Aucune autre équipe disponible');const names=choices.map((t,i)=>`${i+1}. ${t.name}`).join('\n'),n=+prompt('Quelle équipe aider ?\n'+names);if(!n||!choices[n-1])return;helpTeam=choices[n-1].id;$('helpBanner').classList.remove('hidden');$('helpBanner').innerHTML=`🤝 Vous aidez actuellement <b>${esc(choices[n-1].name)}</b> <button class="btn alt" onclick="stopHelp()">Revenir à mon équipe</button>`;renderHouses();renderStats()}
window.stopHelp=()=>{helpTeam=null;$('helpBanner').classList.add('hidden');renderHouses();renderStats()}
function renderMap(){if(!map){map=L.map('map').setView([45.872,3.038],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);map.on('click',e=>map._lastClick=e.latlng)}markers.forEach(m=>m.remove());markers=[];visibleHouses().forEach(h=>{if(h.latitude&&h.longitude){const st=visitFor(h.id)?.status||'a_faire',color=st==='fait'?'green':(['absent','a_repasser'].includes(st)?'orange':st==='refus'?'black':'gray');const m=L.circleMarker([h.latitude,h.longitude],{radius:7,color,fillOpacity:.8}).addTo(map).bindPopup(`<b>${esc(h.house_number||'')} ${esc(h.street||'')}</b><br>${esc(st)}`);markers.push(m)}});setTimeout(()=>map.invalidateSize(),100)}
$('nearMe').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],17);L.circleMarker([p.coords.latitude,p.coords.longitude],{radius:9}).addTo(map).bindPopup('Vous êtes ici').openPopup()},()=>toast('Localisation non disponible'));
$('addHere').onclick=async()=>{const ll=map?._lastClick;if(!ll)return toast("Touchez d'abord l'endroit sur la carte");const street=prompt('Rue / lieu-dit');if(!street)return;const num=prompt('Numéro')||'';const city=cities[0];const sec=sectors[0];if(!sec)return toast("Crée d'abord un secteur");const {error}=await sb.from('households').insert({sector_id:sec.id,house_number:num,street,postal_code:city?.postal_code||'',city_name:city?.name||'',latitude:ll.lat,longitude:ll.lng,active:true});if(error)toast(error.message);else{toast('Maison ajoutée');loadAll()}}
async function renderAdmin(){const p=await sb.from('profiles').select('*').order('full_name');const rs=await sb.from('receipt_settings').select('*').eq('id',true).maybeSingle();if($('receiptConfig'))$('receiptConfig').innerHTML=rs.data?.configured?`<p>✅ Envoi configuré : ${esc(rs.data.sender_email||'')}</p>`:`<p class="muted">⏳ Envoi non configuré. Les reçus peuvent déjà être créés et numérotés.</p>`;if($('receiptSender')&&rs.data?.sender_email)$('receiptSender').value=rs.data.sender_email;$('profiles').innerHTML=(p.data||[]).map(x=>{const mt=members.find(m=>m.user_id===x.id),opts=teams.map(t=>`<option value="${t.id}" ${mt?.team_id===t.id?'selected':''}>${esc(t.name)}</option>`).join('');return `<div class="house"><b>${esc(x.full_name||x.email||'')}</b><div class="muted">${esc(x.email||'')} · ${esc(x.role)}</div><div class="row"><select onchange="adminRole('${x.id}',this.value)">${['admin','responsable','amicaliste'].map(r=>`<option ${x.role===r?'selected':''}>${r}</option>`).join('')}</select><button class="btn ${x.active?'gray':'green'}" onclick="adminActive('${x.id}',${!x.active})">${x.active?'Désactiver':'Activer'}</button></div><br><div class="row"><select onchange="assignMember('${x.id}',this.value,false)"><option value="">Choisir équipe</option>${opts}</select><button class="btn alt" onclick="assignMember('${x.id}',this.previousElementSibling.value,true)">⭐ Responsable équipe</button></div></div>`}).join('');$('citiesAdmin').innerHTML=cities.map(c=>`<span class="pill">${esc(c.name)} ${esc(c.postal_code||'')}</span>`).join('');$('teamsAdmin').innerHTML=teams.map(t=>`<span class="pill">${esc(t.name)}</span>`).join('');renderFilters()}
window.assignMember=async(uid,tid,leader=false)=>{if(!tid)return toast('Choisis une équipe');const {error}=await sb.rpc('assign_member_to_team',{p_user_id:uid,p_team_id:tid,p_leader:leader});if(error)return toast(error.message);toast(leader?'Responsable attribué':'Équipe attribuée');await loadAll()};
window.adminActive=async(id,active)=>{const {error}=await sb.from('profiles').update({active}).eq('id',id);error?toast(error.message):(toast('Compte mis à jour'),renderAdmin())};window.adminRole=async(id,role)=>{const {error}=await sb.from('profiles').update({role}).eq('id',id);error?toast(error.message):toast('Rôle mis à jour')};
$('addCity').onclick=async()=>{const name=$('cityName').value.trim(),postal_code=$('cityPost').value.trim();if(!name)return;const {error}=await sb.from('cities').insert({name,postal_code,active:true});error?toast(error.message):(toast('Commune ajoutée'),loadAll())};$('addTeam').onclick=async()=>{const name=$('teamName').value.trim();if(!name)return;const {error}=await sb.from('teams').insert({campaign_id:campaign.id,name,active:true});error?toast(error.message):(toast('Équipe créée'),loadAll())};
function importLocality(a,city){const v=String(a.locality||a.context||'').trim();return v||city.name}
function importCityName(a,city){return String(a.city||city.name||'').trim()}
function importStreetName(a){return String(a.street||'').trim()||String(a.name||'').replace(/^\s*\d+\s*(?:bis|ter|quater)?\s*/i,'').trim()}
function importHouseNumber(a){const m=String(a.name||a.label||'').match(/^\s*(\d+\s*(?:bis|ter|quater)?)/i);return (m?.[1]||'').trim()}
function normImport(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function addressIdentity(cityName,locality,street,number){return [normImport(cityName),normImport(locality),normImport(street),normImport(number)].join('|')}
function importKey(city,a){return addressIdentity(importCityName(a,city),importLocality(a,city),importStreetName(a),importHouseNumber(a))}
function renderImportedAddresses(city){
 const groups={};
 imported.forEach(a=>{const street=importStreetName(a);if(!street)return;const locality=importLocality(a,city);const lk=locality||city.name;(groups[lk]??={});(groups[lk][street]??=[]).push(a)});
 const blocks=Object.entries(groups).sort(([a],[b])=>a.localeCompare(b,'fr')).map(([locality,roadMap])=>{
   const roads=Object.entries(roadMap).sort(([a],[b])=>a.localeCompare(b,'fr')).map(([street,ads])=>{
     const unique=[];const seen=new Set();for(const a of ads){const k=importKey(city,a);if(!seen.has(k)){seen.add(k);unique.push(a)}}
     const already=unique.filter(a=>{const key=addressIdentity(importCityName(a,city),locality,street,importHouseNumber(a));return households.some(h=>addressIdentity(h.city_name||'',h.locality||'',h.street||'',h.house_number||'')===key)}).length;
     return `<div class="street" style="margin-left:12px"><label><input type="checkbox" class="streetCheck" data-locality="${esc(locality)}" value="${esc(street)}"> <b>${esc(street)}</b></label><div class="muted">${unique.length} adresse(s)${already?` · ${already} déjà enregistrée(s)`:''}</div></div>`
   }).join('');
   const total=Object.values(roadMap).reduce((n,a)=>n+a.length,0);
   return `<div class="street"><div><b>🏘️ ${esc(locality)}</b> <span class="pill">${total} adresse(s)</span></div>${roads}</div>`
 }).join('');
 $('streetImport').innerHTML=`<p class="muted"><b>${imported.length}</b> adresse(s) reçue(s). Classement par hameau / lieu-dit puis par rue. Les adresses déjà présentes ne seront pas recréées.</p>${blocks||'<p class="muted">Aucune voie trouvée.</p>'}`;
}
$('loadAddresses').onclick=async()=>{const city=cities.find(c=>c.id===$('importCity').value);if(!city)return;toast('Recherche des adresses…');const {data,error}=await sb.functions.invoke('import-ban-addresses',{body:{q:city.name,postcode:city.postal_code}});if(error)return toast('Import impossible : '+error.message);imported=data?.items||[];renderImportedAddresses(city);toast(`${imported.length} adresse(s) trouvée(s)`)};
$('assignChecked').onclick=async()=>{const city=cities.find(c=>c.id===$('importCity').value),team=$('assignTeam').value,checks=[...document.querySelectorAll('.streetCheck:checked')];if(!city||!team||!checks.length)return toast('Coche au moins une rue');let sec=sectors.find(s=>s.city_id===city.id);if(!sec){const r=await sb.from('sectors').insert({city_id:city.id,name:city.name,active:true}).select().single();if(r.error)return toast(r.error.message);sec=r.data;sectors.push(sec)}
 let added=0,skipped=0;
 for(const check of checks){const name=check.value,locality=check.dataset.locality||city.name;let st=streets.find(s=>s.city_id===city.id&&normImport(s.name)===normImport(name)&&normImport(s.locality||'')===normImport(locality));
   if(!st){const r=await sb.from('streets').insert({city_id:city.id,name,locality,active:true}).select().single();if(r.error){toast('Rue non créée : '+r.error.message);continue}st=r.data;streets.push(st)}
   await sb.from('team_streets').delete().eq('street_id',st.id);const tr=await sb.from('team_streets').insert({team_id:team,street_id:st.id});if(tr.error){toast('Attribution impossible : '+tr.error.message);continue}
   const ads=imported.filter(a=>normImport(importStreetName(a))===normImport(name)&&normImport(importLocality(a,city))===normImport(locality));
   const seen=new Set();
   for(const a of ads){const houseNumber=importHouseNumber(a),key=addressIdentity(importCityName(a,city),locality,name,houseNumber);if(seen.has(key)){skipped++;continue}seen.add(key);
     const exists=households.some(h=>addressIdentity(h.city_name||'',h.locality||'',h.street||'',h.house_number||'')===key);
     if(exists){skipped++;continue}
     const r=await sb.from('households').insert({sector_id:sec.id,street_id:st.id,house_number:houseNumber,street:name,locality,postal_code:a.postcode||city.postal_code,city_name:a.city||city.name,latitude:a.lat,longitude:a.lon,active:true});
     if(!r.error){added++;households.push({sector_id:sec.id,street_id:st.id,house_number:houseNumber,street:name,locality,postal_code:a.postcode||city.postal_code,city_name:a.city||city.name,latitude:a.lat,longitude:a.lon,active:true})}
   }
 }
 toast(`${added} maison(s) ajoutée(s) · ${skipped} doublon(s) évité(s)`);await loadAll()};
$('assignWholeCity').onclick=async()=>{const city=$('importCity').value,team=$('assignTeam').value;if(!city||!team)return toast('Choisis le village et l’équipe');if(!confirm('Attribuer toutes les rues déjà importées de ce village à cette équipe ?'))return;const {data,error}=await sb.rpc('assign_city_streets_to_team',{p_city_id:city,p_team_id:team});if(error)return toast(error.message);toast(`${data||0} rue(s) attribuée(s)`);await loadAll()};
$('saveReceiptEmail').onclick=async()=>{const email=$('receiptSender').value.trim();if(!email)return toast('Saisis l’adresse Gmail dédiée');const {error}=await sb.from('receipt_settings').update({sender_email:email,provider:'gmail',configured:false,enabled:false,updated_at:new Date().toISOString(),updated_by:me.id}).eq('id',true);if(error)return toast(error.message);toast('Adresse enregistrée. La connexion sécurisée pourra être faite plus tard.');await renderAdmin()};
$('testModeBtn').onclick=async()=>{const next=!campaign.test_mode;if(!confirm(next?'Activer le mode test ?':'Quitter le mode test ?'))return;const {error}=await sb.from('campaigns').update({test_mode:next}).eq('id',campaign.id);if(error)return toast(error.message);toast(next?'🧪 Mode test activé':'Mode réel activé');await loadAll()};



let lastVisitSnapshot=null;
function myTeamId(){return members.find(x=>x.user_id===me.id)?.team_id||null}
function queueIndicator(){const n=JSON.parse(localStorage.getItem('visitQueue')||'[]').length;if($('netQueue'))$('netQueue').textContent=n?`🟠 ${n} modification(s) à synchroniser`:'🟢 Synchronisé'}
if($('smartNow')) $('smartNow').onclick=()=>{if($('filterStatus')){$('filterStatus').value='a_repasser';renderHouses()}toast('Priorité aux maisons à repasser')}
if($('undoLast')) $('undoLast').onclick=async()=>{if(!lastVisitSnapshot)return toast('Aucune action récente à annuler');const s=lastVisitSnapshot;if(s.wasNew){await sb.from('visits').delete().eq('id',s.id)}else{await sb.from('visits').update(s.old).eq('id',s.id)}lastVisitSnapshot=null;await loadAll();toast('Dernière action annulée')}
if($('endDay')) $('endDay').onclick=async()=>{const tid=myTeamId();if(!tid)return toast('Aucune équipe attribuée');const previous=(await sb.from('tour_closings').select('period_end').eq('campaign_id',campaign.id).eq('team_id',tid).eq('closing_type','day').order('period_end',{ascending:false}).limit(1).maybeSingle()).data;const since=previous?.period_end||new Date(new Date().setHours(0,0,0,0)).toISOString();const vv=visits.filter(v=>v.team_id===tid&&v.status==='fait'&&new Date(v.visited_at||v.updated_at)>=new Date(since)),sum=k=>vv.filter(v=>v.payment_method===k).reduce((a,v)=>a+(+v.amount||0),0),cal=vv.reduce((a,v)=>a+(+v.calendars_count||0),0),rev=visits.filter(v=>v.team_id===tid&&(v.status==='a_repasser'||v.status==='absent')).length;const {data:allProfiles}=await sb.from('profiles').select('*').eq('active',true);const mates=(allProfiles||[]).filter(p=>p.id!==me.id).sort((a,b)=>(a.full_name||'').localeCompare(b.full_name||''));let partner=null;const choices=mates.map((p,i)=>`${i+1}. ${p.full_name}`).join('\n');const otherNo=mates.length+1;const pick=prompt(`Avec qui avez-vous effectué les passages aujourd'hui ?\n\n${choices}${choices?'\n':''}${otherNo}. 👤 Autre personne / ancien pompier\n\nSaisissez le numéro :`,'1');if(pick===null)return;const n=Number(pick);if(n===otherNo){const partnerName=prompt("Nom et prénom de l'ancien pompier / accompagnant",'');if(partnerName===null)return;const nm=partnerName.trim();if(!nm)return toast('Nom du binôme requis');const {data:eh,error:ee}=await sb.from('external_helpers').insert({full_name:nm,created_by:me.id}).select().single();if(ee)return toast(ee.message);partner={id:null,full_name:eh.full_name}}else{partner=mates[n-1];if(!partner)return toast('Binôme invalide')};const counted=prompt(`FIN DE JOURNÉE\n\nCette opération ne termine PAS la tournée.\n\nBinôme : ${me.full_name||'Moi'} + ${partner?.full_name||'Non renseigné'}\n\nCalendriers aujourd'hui : ${cal}\nEspèces attendues : ${money(sum('especes'))}\nChèques : ${money(sum('cheque'))}\nCarte : ${money(sum('carte'))}\nMaisons encore à repasser/absentes : ${rev}\n\nEspèces réellement comptées ?`,Number(sum('especes')).toFixed(2));if(counted===null)return;const c=Number(String(counted).replace(',','.'));if(Number.isNaN(c))return toast('Montant invalide');const {error}=await sb.from('tour_closings').insert({campaign_id:campaign.id,team_id:tid,user_id:me.id,partner_user_id:partner?.id||null,partner_name_snapshot:partner?.full_name||null,closing_type:'day',period_start:since,period_end:new Date().toISOString(),expected_cash:sum('especes'),counted_cash:c,expected_cheque:sum('cheque'),expected_card:sum('carte'),expected_other:sum('autre'),calendars_count:cal,completed_count:vv.length,revisit_count:rev});if(error)return toast(error.message);toast(Math.abs(c-sum('especes'))<0.005?'✅ Fin de journée enregistrée — caisse conforme':'⚠️ Fin de journée enregistrée — écart de caisse : '+money(c-sum('especes')))}
if($('completeTour')) $('completeTour').onclick=async()=>{const tid=myTeamId();if(!tid)return toast('Aucune équipe attribuée');const remaining=households.filter(h=>{const v=visitFor(h.id);return !v||!['fait','refus'].includes(v.status)}).length;if(remaining>0&&!confirm(`Il reste ${remaining} maison(s) non terminée(s).\n\nVoulez-vous vraiment déclarer la TOURNÉE TERMINÉE ?`))return;if(!confirm('🏁 CONFIRMATION\n\nLa tournée est-elle réellement terminée pour cette équipe ?\n\nUtilisez Fin de journée si vous reprenez un autre jour.'))return;const {error}=await sb.from('team_tour_completions').insert({campaign_id:campaign.id,team_id:tid,completed_by:me.id});if(error){if(error.code==='23505')return toast('Cette tournée est déjà marquée terminée');return toast(error.message)}toast('🏁 Tournée marquée comme terminée')}
if($('prepareNext')) $('prepareNext').onclick=async()=>{const y=Number(prompt('Année de la nouvelle campagne',String(Number(campaign.year)+1)));if(!y)return;if(!confirm(`Créer la campagne ${y} à partir de ${campaign.year} ?\nLes équipes, membres, secteurs et rues seront conservés. Les visites repartiront à zéro.`))return;const {error}=await sb.rpc('create_next_campaign',{p_source_campaign:campaign.id,p_year:y});if(error)return toast(error.message);toast(`Campagne ${y} préparée`);await loadAll()}
if($('closeCampaign')) $('closeCampaign').onclick=async()=>{if(!confirm(`ATTENTION\n\nClôturer définitivement la campagne ${campaign.year} ?\nLes données financières de cette campagne ne devront plus être modifiées.`))return;const txt=prompt(`Pour confirmer, écrivez : CLOTURER ${campaign.year}`,'');if(txt!==`CLOTURER ${campaign.year}`)return toast('Clôture annulée');const {error}=await sb.rpc('close_campaign',{p_campaign_id:campaign.id});if(error)return toast(error.message);toast(`🔒 Campagne ${campaign.year} clôturée`);await loadAll()}
queueIndicator();window.addEventListener('online',queueIndicator);window.addEventListener('offline',queueIndicator);

function money(v){return `${Number(v||0).toFixed(2).replace('.',',')} €`}
function payLabel(v){return ({especes:'Espèces',carte:'Carte',cheque:'Chèque',autre:'Autre'})[v]||v||''}
function pdfBase(title){const {jsPDF}=window.jspdf,d=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});d.setFontSize(16);d.text('Amicale des Sapeurs-Pompiers de Volvic',14,16);d.setFontSize(13);d.text(title,14,24);d.setFontSize(9);d.text(`Campagne ${campaign.year} • Généré le ${new Date().toLocaleString('fr-FR')}`,14,30);return d}
$('pdfReceipts').onclick=async()=>{const rr=await getReceipts(),d=pdfBase('Registre des reçus');d.autoTable({startY:36,head:[['N°','Date','Nom / adresse','Montant','Paiement','Cal.']],body:rr.map(r=>[r.receipt_number,new Date(r.issued_at).toLocaleDateString('fr-FR'),`${r.recipient_name||''}\n${r.recipient_address||''}\n${r.recipient_postal_code||''} ${r.recipient_city||''}`,money(r.amount),payLabel(r.payment_method),r.calendars_count||0]),styles:{fontSize:7,cellPadding:1.5},headStyles:{fontSize:7}});d.save(`registre-recus-${campaign.year}.pdf`)}
$('pdfTeams').onclick=async()=>{const {data,error}=await sb.from('campaign_team_summary').select('*').eq('campaign_id',campaign.id).order('team_name');if(error)return toast(error.message);const d=pdfBase('Bilans par équipe');d.autoTable({startY:36,head:[['Équipe','Prévus','Faits','Cal.','Total','Espèces','Carte','Chèque','Autre']],body:(data||[]).map(r=>[r.team_name,r.planned_households,r.completed_households,r.calendars,money(r.total_amount),money(r.cash_amount),money(r.card_amount),money(r.cheque_amount),money(r.other_amount)]),styles:{fontSize:7,cellPadding:1.4},headStyles:{fontSize:7}});d.save(`bilans-equipes-${campaign.year}.pdf`)}
$('pdfGlobal').onclick=async()=>{const {data:g,error}=await sb.from('campaign_global_summary').select('*').eq('campaign_id',campaign.id).single();if(error)return toast(error.message);const d=pdfBase('Bilan général');d.autoTable({startY:38,body:[['Foyers enregistrés',households.length],['Foyers réalisés',g.completed_households],['Absents',g.absent_households],['À repasser',g.revisit_households],['Refus',g.refused_households],['Calendriers distribués',g.calendars],['Total des versements',money(g.total_amount)],['Espèces',money(g.cash_amount)],['Carte',money(g.card_amount)],['Chèque',money(g.cheque_amount)],['Autre',money(g.other_amount)]],styles:{fontSize:11,cellPadding:3},columnStyles:{0:{fontStyle:'bold'}}});d.save(`bilan-general-${campaign.year}.pdf`)}
$('excelCampaign').onclick=async()=>{if(!window.XLSX)return toast('Module Excel indisponible');const rr=await getReceipts(),{data:tt,error}=await sb.from('campaign_team_summary').select('*').eq('campaign_id',campaign.id).order('team_name');if(error)return toast(error.message);const vv=visits.filter(v=>v.status==='fait'),sum=k=>vv.filter(v=>!k||v.payment_method===k).reduce((a,v)=>a+(+v.amount||0),0),wb=XLSX.utils.book_new();const global=[['Bilan général',campaign.year],['Foyers enregistrés',households.length],['Foyers réalisés',vv.length],['Calendriers distribués',vv.reduce((a,v)=>a+(+v.calendars_count||0),0)],['Total versements',sum()],['Espèces',sum('especes')],['Carte',sum('carte')],['Chèque',sum('cheque')],['Autre',sum('autre')]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(global),'Bilan général');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((tt||[]).map(r=>({'Équipe':r.team_name,'Foyers prévus':r.planned_households,'Foyers faits':r.completed_households,'Calendriers':r.calendars,'Total':Number(r.total_amount||0),'Espèces':Number(r.cash_amount||0),'Carte':Number(r.card_amount||0),'Chèque':Number(r.cheque_amount||0),'Autre':Number(r.other_amount||0)}))),'Équipes');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rr.map(r=>({'N° reçu':r.receipt_number,'Date':new Date(r.issued_at).toLocaleString('fr-FR'),'Nom Prénom':r.recipient_name,'Adresse':r.recipient_address,'Code postal':r.recipient_postal_code,'Commune':r.recipient_city,'E-mail':r.recipient_email,'Montant':Number(r.amount||0),'Paiement':payLabel(r.payment_method),'Calendriers':r.calendars_count,'Statut envoi':r.delivery_status}))),'Reçus');XLSX.writeFile(wb,`bilan-calendriers-${campaign.year}.xlsx`)}

function dl(name,text,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(rows){return rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(';')).join('\n')}
async function getReceipts(){const {data,error}=await sb.from('receipts').select('*').eq('campaign_id',campaign.id).order('issued_at');if(error){toast(error.message);return[]}return data||[]}
$('exportReceipts').onclick=async()=>{const rr=await getReceipts();const rows=[['N° reçu','Date','Nom Prénom','Adresse','Code postal','Commune','E-mail','Montant','Paiement','Calendriers','Statut envoi']];rr.forEach(r=>rows.push([r.receipt_number,new Date(r.issued_at).toLocaleString('fr-FR'),r.recipient_name,r.recipient_address,r.recipient_postal_code,r.recipient_city,r.recipient_email,r.amount,r.payment_method,r.calendars_count,r.delivery_status]));dl(`registre-recus-${campaign.year}.csv`,csv(rows))}
$('exportTeams').onclick=async()=>{const {data,error}=await sb.from('campaign_team_summary').select('*').eq('campaign_id',campaign.id).order('team_name');if(error)return toast(error.message);const rows=[['Équipe','Foyers prévus','Foyers faits','Calendriers','Total dons','Espèces','Carte','Chèque','Autre']];(data||[]).forEach(r=>rows.push([r.team_name,r.planned_households,r.completed_households,r.calendars,r.total_amount,r.cash_amount,r.card_amount,r.cheque_amount,r.other_amount]));dl(`bilans-equipes-${campaign.year}.csv`,csv(rows))}
$('exportGlobal').onclick=()=>{const vv=visits.filter(v=>v.status==='fait'),sum=k=>vv.filter(v=>!k||v.payment_method===k).reduce((a,v)=>a+(+v.amount||0),0),cal=vv.reduce((a,v)=>a+(+v.calendars_count||0),0);const rows=[['BILAN GÉNÉRAL CAMPAGNE',campaign.year],['Foyers enregistrés',households.length],['Foyers faits',vv.length],['Calendriers distribués',cal],['Total dons',sum()],['Espèces',sum('especes')],['Carte',sum('carte')],['Chèque',sum('cheque')],['Autre',sum('autre')]];dl(`bilan-total-${campaign.year}.csv`,csv(rows))}
$('exportAll').onclick=async()=>{const rr=await getReceipts();const {data:tt}=await sb.from('campaign_team_summary').select('*').eq('campaign_id',campaign.id).order('team_name');let rows=[['ARCHIVE COMPLÈTE - AMICALE SP VOLVIC'],['Campagne',campaign.year],[],['BILAN TOTAL'],['Foyers','Calendriers','Total dons','Espèces','Carte','Chèque','Autre']];const vv=visits.filter(v=>v.status==='fait'),sum=k=>vv.filter(v=>!k||v.payment_method===k).reduce((a,v)=>a+(+v.amount||0),0);rows.push([vv.length,vv.reduce((a,v)=>a+(+v.calendars_count||0),0),sum(),sum('especes'),sum('carte'),sum('cheque'),sum('autre')],[],['BILANS PAR ÉQUIPE'],['Équipe','Prévus','Faits','Calendriers','Total','Espèces','Carte','Chèque','Autre']);(tt||[]).forEach(r=>rows.push([r.team_name,r.planned_households,r.completed_households,r.calendars,r.total_amount,r.cash_amount,r.card_amount,r.cheque_amount,r.other_amount]));rows.push([],['REGISTRE DES REÇUS'],['N° reçu','Date','Nom Prénom','Adresse','CP','Commune','E-mail','Montant','Paiement','Calendriers']);rr.forEach(r=>rows.push([r.receipt_number,new Date(r.issued_at).toLocaleString('fr-FR'),r.recipient_name,r.recipient_address,r.recipient_postal_code,r.recipient_city,r.recipient_email,r.amount,r.payment_method,r.calendars_count]));dl(`archive-complete-calendriers-${campaign.year}.csv`,csv(rows))}

$('exportCsv').onclick=()=>{const rows=[['Adresse','Village','Statut','Calendriers','Montant','Paiement','Commentaire']];households.forEach(h=>{const v=visitFor(h.id)||{};rows.push([`${h.house_number||''} ${h.street||''}`,h.locality||h.city_name||'',v.status||'a_faire',v.calendars_count||0,v.amount||0,v.payment_method||'',v.visit_comment||''])});const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`tournees-${campaign.year}.csv`;a.click()};
function subscribe(){sb.removeAllChannels();sb.channel('live-v9').on('postgres_changes',{event:'*',schema:'public',table:'visits'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'households'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'visit_presence'},()=>loadAll()).subscribe()}
window.page=function(name){['home','tour','map','admin','settings'].forEach(x=>$('page-'+x).classList.toggle('hidden',x!==name));if(name==='map')renderMap();if(name==='tour')renderHouses()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('sectorSelect').onchange=renderHouses;$('teamView').onchange=renderHouses;$('filterStatus').onchange=renderHouses;$('searchHouse').oninput=renderHouses;$('refreshBtn').onclick=loadAll;$('logoutBtn').onclick=()=>sb.auth.signOut();
$('loginBtn').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'Connexion…'};$('signupBtn').onclick=async()=>{const full=prompt('Prénom et nom');if(!full)return;const {error}=await sb.auth.signUp({email:$('email').value.trim(),password:$('password').value,options:{data:{full_name:full}}});$('authMsg').textContent=error?error.message:'Compte créé. Vérifie ton e-mail si demandé.'};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));boot();