const SUPABASE_URL='https://glttqzvewnchpddtkfde.supabase.co';
const SUPABASE_KEY='sb_publishable_lazb-Ub8XQE83jSMHOj7LQ_PdugUzSr';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id); let me=null,campaign=null,sectors=[],households=[],visits=[],teams=[],map=null,markers=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
async function boot(){const {data:{session}}=await sb.auth.getSession(); if(session) await enter(session.user); else showAuth(); sb.auth.onAuthStateChange(async(e,s)=>{if(e==='SIGNED_IN'&&s) await enter(s.user);if(e==='SIGNED_OUT')showAuth()})}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('tabs').classList.add('hidden')}
async function enter(user){const {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error){$('authMsg').textContent='Compte créé. Vérifie ton e-mail puis reconnecte-toi.';return}me=p;if(!p.active){$('authMsg').textContent='Ton compte attend la validation de l’administrateur.';await sb.auth.signOut();return}$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('tabs').classList.remove('hidden');document.body.classList.toggle('isAdmin',p.role==='admin');$('who').textContent=`${p.full_name||p.email} · ${p.role}`;$('profileInfo').innerHTML=`<b>${esc(p.full_name||'')}</b><br>${esc(p.email||'')}<br><span class="pill">${esc(p.role)}</span>`;await loadAll();subscribe();page('home')}
async function loadAll(){setSync('Synchronisation…');const c=await sb.from('campaigns').select('*').eq('active',true).order('year',{ascending:false}).limit(1).maybeSingle();campaign=c.data;if(!campaign){setSync('Aucune campagne active');return}$('campaignYear').textContent=campaign.year;
let secQ=sb.from('sectors').select('*,cities(name,postal_code)').eq('active',true).order('name');const sec=await secQ;sectors=sec.data||[];
const h=await sb.from('households').select('*').eq('active',true).order('street').order('house_number');households=h.data||[];
const v=await sb.from('visits').select('*').eq('campaign_id',campaign.id);visits=v.data||[];
const t=await sb.from('teams').select('*').eq('campaign_id',campaign.id);teams=t.data||[];renderSectors();renderHouses();renderStats();renderMap();if(me.role==='admin')await renderAdmin();setSync('À jour')}
function setSync(s){$('syncState').textContent=s}
function visitFor(id){return visits.find(v=>v.household_id===id)}
function renderStats(){let done=0,redo=0,cal=0,amt=0,pay={};for(const v of visits){if(v.status==='fait')done++;if(['absent','a_repasser'].includes(v.status))redo++;cal+=Number(v.calendars_count||0);amt+=Number(v.amount||0);if(v.payment_method)pay[v.payment_method]=(pay[v.payment_method]||0)+Number(v.amount||0)}$('sTotal').textContent=households.length;$('sDone').textContent=done;$('sRedo').textContent=redo;$('sRemain').textContent=Math.max(0,households.length-done);$('sCalendars').textContent=cal;$('sAmount').textContent=amt.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});$('paymentStats').textContent=Object.entries(pay).map(([k,v])=>`${k}: ${v.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}`).join(' · ')||'Aucun encaissement enregistré'}
function renderSectors(){const opts=sectors.map(s=>`<option value="${s.id}">${esc(s.cities?.name||'')} — ${esc(s.name)}</option>`).join('');$('sectorSelect').innerHTML='<option value="">Tous mes secteurs</option>'+opts;$('sectorButtons').innerHTML=sectors.map(s=>`<button class="btn alt" style="margin:4px" onclick="openSector('${s.id}')">${esc(s.cities?.name||'')} · ${esc(s.name)}</button>`).join('')||'<span class="muted">Aucun secteur attribué.</span>'}
window.openSector=id=>{$('sectorSelect').value=id;page('tour');renderHouses()};
function renderHouses(){if(!$('houses'))return;const sid=$('sectorSelect').value,fs=$('filterStatus').value,q=$('searchHouse').value.toLowerCase();let list=households.filter(h=>(!sid||h.sector_id===sid));list=list.filter(h=>{const v=visitFor(h.id),st=v?.status||'a_faire';return(!fs||st===fs)&&(`${h.house_number||''} ${h.street||''} ${h.locality||''}`.toLowerCase().includes(q))});$('houses').innerHTML=list.map(h=>houseHTML(h)).join('')||'<div class="card muted">Aucun foyer correspondant.</div>'}
function houseHTML(h){const v=visitFor(h.id)||{},st=v.status||'a_faire',cl=st==='fait'?'done':st==='refus'?'refus':(['absent','a_repasser'].includes(st)?'absent':'');return `<div class="house ${cl}" id="h-${h.id}"><b>${esc(h.house_number||'')} ${esc(h.street||'')}</b><div class="muted">${esc(h.locality||'')} ${esc(h.postal_code||'')} ${esc(h.city_name||'')}</div>${h.note_category?`<span class="pill">${esc(h.note_category)}</span>`:''}${h.preferred_time?`<span class="pill">🕒 ${esc(h.preferred_time)}</span>`:''}${h.permanent_note?`<div class="muted">📝 ${esc(h.permanent_note)}</div>`:''}<div class="status">${[['a_faire','À faire'],['fait','Fait'],['absent','Absent'],['a_repasser','À repasser'],['refus','Refus']].map(x=>`<button class="${st===x[0]?'on':''}" onclick="quickStatus('${h.id}','${x[0]}')">${x[1]}</button>`).join('')}</div><div class="grid g2"><input id="cal-${h.id}" type="number" min="0" inputmode="numeric" placeholder="Calendriers" value="${v.calendars_count??''}"><input id="amt-${h.id}" type="number" min="0" step="0.01" inputmode="decimal" placeholder="Don €" value="${v.amount??''}"><select id="pay-${h.id}"><option value="">Paiement</option>${['especes','carte','cheque','autre'].map(x=>`<option ${v.payment_method===x?'selected':''}>${x}</option>`).join('')}</select><input id="com-${h.id}" placeholder="Commentaire visite" value="${esc(v.visit_comment||'')}"></div><div class="row" style="margin-top:8px"><button class="btn" onclick="saveVisit('${h.id}')">Enregistrer</button><button class="btn alt" onclick="editNote('${h.id}')">Note permanente</button></div></div>`}
window.quickStatus=async(id,status)=>{await saveVisit(id,status)};
window.saveVisit=async(id,statusOverride)=>{if(!campaign)return;const old=visitFor(id)||{};const payload={campaign_id:campaign.id,household_id:id,team_id:old.team_id||null,status:statusOverride||old.status||'fait',calendars_count:Number($('cal-'+id)?.value||0),amount:Number($('amt-'+id)?.value||0),payment_method:$('pay-'+id)?.value||null,visit_comment:$('com-'+id)?.value||null,visited_by:me.id,visited_at:new Date().toISOString(),updated_at:new Date().toISOString()};setSync('Enregistrement…');const {data,error}=await sb.from('visits').upsert(payload,{onConflict:'campaign_id,household_id'}).select().single();if(error){toast('Erreur : '+error.message);setSync('Erreur de synchro');return}const i=visits.findIndex(v=>v.household_id===id);if(i>=0)visits[i]=data;else visits.push(data);renderHouses();renderStats();setSync('À jour');toast('Enregistré')}
window.editNote=async id=>{const h=households.find(x=>x.id===id);const note=prompt('Note permanente (visible les années suivantes)',h.permanent_note||'');if(note===null)return;const cat=prompt('Catégorie : Personne âgée / Horaire particulier / Accès-portail / autre',h.note_category||'');if(cat===null)return;const time=prompt('Horaire conseillé : matin / midi / après-midi / avant 18 h / soir',h.preferred_time||'');if(time===null)return;const {data,error}=await sb.rpc('update_household_note',{p_household_id:id,p_permanent_note:note,p_note_category:cat,p_preferred_time:time});if(error)return toast(error.message);Object.assign(h,data);renderHouses();toast('Note enregistrée')}
function renderMap(){if(!map){map=L.map('map').setView([45.872,3.038],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}markers.forEach(m=>m.remove());markers=[];for(const h of households){if(h.latitude&&h.longitude){const v=visitFor(h.id),m=L.marker([h.latitude,h.longitude]).addTo(map).bindPopup(`<b>${esc(h.house_number||'')} ${esc(h.street||'')}</b><br>${v?.status||'À faire'}`);markers.push(m)}}setTimeout(()=>map.invalidateSize(),150)}
async function renderAdmin(){const [p,c]=await Promise.all([sb.from('profiles').select('*').order('full_name'),sb.from('cities').select('*').order('name')]);$('profiles').innerHTML=(p.data||[]).map(x=>`<div class="house"><b>${esc(x.full_name||x.email||'')}</b><div class="muted">${esc(x.email||'')} · ${esc(x.role)}</div><div class="row"><select onchange="adminRole('${x.id}',this.value)">${['admin','responsable','amicaliste'].map(r=>`<option ${x.role===r?'selected':''}>${r}</option>`).join('')}</select><button class="btn ${x.active?'gray':'green'}" onclick="adminActive('${x.id}',${!x.active})">${x.active?'Désactiver':'Activer'}</button></div></div>`).join('');const cities=c.data||[];$('citiesAdmin').innerHTML=cities.map(x=>`<span class="pill">${esc(x.name)} ${esc(x.postal_code||'')}</span>`).join('');$('cityForSector').innerHTML=cities.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('teamsAdmin').innerHTML=teams.map(x=>`<span class="pill">${esc(x.name)}</span>`).join('')}
window.adminActive=async(id,active)=>{const {error}=await sb.from('profiles').update({active}).eq('id',id);if(error)toast(error.message);else{toast('Compte mis à jour');renderAdmin()}};window.adminRole=async(id,role)=>{const {error}=await sb.from('profiles').update({role}).eq('id',id);if(error)toast(error.message);else toast('Rôle mis à jour')};
$('addCity').onclick=async()=>{const {error}=await sb.from('cities').insert({name:$('cityName').value.trim(),postal_code:$('cityPost').value.trim(),active:true});if(error)toast(error.message);else{toast('Ville ajoutée');renderAdmin();loadAll()}};$('addSector').onclick=async()=>{const {error}=await sb.from('sectors').insert({city_id:$('cityForSector').value,name:$('sectorName').value.trim(),active:true});if(error)toast(error.message);else{toast('Secteur ajouté');loadAll()}};$('addTeam').onclick=async()=>{const {error}=await sb.from('teams').insert({campaign_id:campaign.id,name:$('teamName').value.trim(),active:true});if(error)toast(error.message);else{toast('Équipe créée');loadAll()}};
function subscribe(){sb.removeAllChannels();sb.channel('live').on('postgres_changes',{event:'*',schema:'public',table:'visits'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'households'},()=>loadAll()).subscribe()}
function page(name){['home','tour','map','admin','settings'].forEach(x=>$('page-'+x).classList.toggle('hidden',x!==name));if(name==='map')renderMap();if(name==='tour')renderHouses()}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('sectorSelect').onchange=renderHouses;$('filterStatus').onchange=renderHouses;$('searchHouse').oninput=renderHouses;$('refreshBtn').onclick=loadAll;$('logoutBtn').onclick=()=>sb.auth.signOut();
$('loginBtn').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authMsg').textContent=error?error.message:'Connexion…'};$('signupBtn').onclick=async()=>{const full=prompt('Prénom et nom');if(!full)return;const {error}=await sb.auth.signUp({email:$('email').value.trim(),password:$('password').value,options:{data:{full_name:full}}});$('authMsg').textContent=error?error.message:'Compte créé. Vérifie ton e-mail si Supabase te le demande.'};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));boot();